version: "3.0"
services:
  tensorflow-cpu:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "boilerplate"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      MODEL_ZIP_DOWNLOAD_URL: "https://drive.google.com/uc?export=download&id=1-abcdefgh"
      MODEL_LOCAL_FOLDERPATH: ""
      IS_KERAS: "True"
      FORWARD_PROP_FUNCTION: "__call__"
      INPUT_LABELS: "temp, volume, pressure, mass, rpm, speed, density, id"
      OUTPUT_LABEL: "prediction"
    ports:
      - 80:80
